kumuluzee:
  name: "grpc-server"
  server:
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/UsersDB
      connection-url: jdbc:postgresql://localhost:5432/users
      username: postgres
      password: postgres
  grpc:
    server:
#      https:
#        enable: true
#        port: 8443
#        certFile: ../certs/server.crt
#        keyFile: ../certs/server.key
#        chainFile: ../certs/rootCA.crt
#        mutualTLS: require
      conf:
#        permitKeepAliveTime: 60000
#        permitKeepAliveWithoutCalls: true
#        keepAliveTimeout: 60000
#        keepAliveTime: 60000
#        maxConnectionIdle: 60000
        maxConnectionAge: 60000
#        maxConnectionAgeGrace: 60000
      health:
        healthCheckEnabled: true
      reflection:
        reflectionEnabled: true
      http:
        port: 8081
      auth:
        maximum-leeway: 100
        public-key: "-----BEGIN PUBLIC KEY-----
                      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArM5dnb8m8YJP7jE4+mzk
                      m77bcPocec1ECgIRGsq15xMZDlVRngVVyAeU681k7wCvQaQManHKQPnD6Ky4LDoO
                      5v9uc4nhdboPyW47LloRfUe17fjEZVbf/XXSIh65PNJXNTwbIbDSraRccUVCPG8b
                      JO4Ed6NGlXJzfjH3L/W1tSrN2FE93hNnbc5lO0btz9Yefj0XRe6E2K0wj1wIy6YZ
                      ExY6RQILsLiC2l/yad6fKScpiZ89VprcKZ59SYOkWasgXfUyayICgLxmkpmZUS3S
                      V4NLFCVJKKw7azTZwYKUOeWrylfGv82sderKPhjvjPG8JAJqRj2b231f8/OS65Ti
                      zwIDAQAB
                      -----END PUBLIC KEY-----"

#        public-key: "{\n\"keys\": [\n{\n\"alg\": \"RS256\",\n\"e\": \"AQAB\",\n\"key_ops\": null,\n\"kid\": \"ts2cv5Vjrf51VuLGJ38DVWl23UbowceopzQoV_0v7uM\",\n\"kty\": \"RSA\",\n\"n\": \"2AWirUxwLKDhSjNIc9NS7XqEgNi643qqNwTbcWYNiIFXxbBXOtaDCSemn4TSBcaTFdYUBdhNZeOYeBnZb565ipQXn60X2-zubtb33W3G1uswNn8FqDLDIjPtAC7nryVYIUSukeuggYUrHMBAuGwSqsBsGgL7SfRc74eNg-qi13pN3jeFfukA1f73inOr9IGWASTRSO_ZtUpnC2AjmN8GM-XicuFUduKl3EaeDtptBfKcu4Td9N7jH1PuGgsZ21_VXpwV_jPmTM1pZ5p_oplT9Ub1QWi-8Wvc-y8ZuRmjlks4Mg5m_h0ruYAI1S_3I4cf5zxXVP2hE9_id-0QQZ3mEw\",\n\"use\": \"sig\"\n}\n]\n}"
#        public-key: "ewoia2V5cyI6IFsKewoiYWxnIjogIlJTMjU2IiwKImUiOiAiQVFBQiIsCiJrZXlfb3BzIjogbnVsbCwKImtpZCI6ICJ0czJjdjVWanJmNTFWdUxHSjM4RFZXbDIzVWJvd2Nlb3B6UW9WXzB2N3VNIiwKImt0eSI6ICJSU0EiLAoibiI6ICIyQVdpclV4d0xLRGhTak5JYzlOUzdYcUVnTmk2NDNxcU53VGJjV1lOaUlGWHhiQlhPdGFEQ1NlbW40VFNCY2FURmRZVUJkaE5aZU9ZZUJuWmI1NjVpcFFYbjYwWDItenVidGIzM1czRzF1c3dObjhGcURMRElqUHRBQzducnlWWUlVU3VrZXVnZ1lVckhNQkF1R3dTcXNCc0dnTDdTZlJjNzRlTmctcWkxM3BOM2plRmZ1a0ExZjczaW5PcjlJR1dBU1RSU09fWnRVcG5DMkFqbU44R00tWGljdUZVZHVLbDNFYWVEdHB0QmZLY3U0VGQ5TjdqSDFQdUdnc1oyMV9WWHB3Vl9qUG1UTTFwWjVwX29wbFQ5VWIxUVdpLThXdmMteThadVJtamxrczRNZzVtX2gwcnVZQUkxU18zSTRjZjV6eFhWUDJoRTlfaWQtMFFRWjNtRXciLAoidXNlIjogInNpZyIKfQpdCn0="
#        public-key: "{\n  \"alg\": \"RS256\",\n  \"e\": \"AQAB\",\n  \"key_ops\": null,\n  \"kid\": \"ts2cv5Vjrf51VuLGJ38DVWl23UbowceopzQoV_0v7uM\",\n  \"kty\": \"RSA\",\n  \"n\": \"2AWirUxwLKDhSjNIc9NS7XqEgNi643qqNwTbcWYNiIFXxbBXOtaDCSemn4TSBcaTFdYUBdhNZeOYeBnZb565ipQXn60X2-zubtb33W3G1uswNn8FqDLDIjPtAC7nryVYIUSukeuggYUrHMBAuGwSqsBsGgL7SfRc74eNg-qi13pN3jeFfukA1f73inOr9IGWASTRSO_ZtUpnC2AjmN8GM-XicuFUduKl3EaeDtptBfKcu4Td9N7jH1PuGgsZ21_VXpwV_jPmTM1pZ5p_oplT9Ub1QWi-8Wvc-y8ZuRmjlks4Mg5m_h0ruYAI1S_3I4cf5zxXVP2hE9_id-0QQZ3mEw\",\n  \"use\": \"sig\"\n}"
#        public-key: "ewoiYWxnIjogIlJTMjU2IiwKImUiOiAiQVFBQiIsCiJrZXlfb3BzIjogbnVsbCwKImtpZCI6ICJ0czJjdjVWanJmNTFWdUxHSjM4RFZXbDIzVWJvd2Nlb3B6UW9WXzB2N3VNIiwKImt0eSI6ICJSU0EiLAoibiI6ICIyQVdpclV4d0xLRGhTak5JYzlOUzdYcUVnTmk2NDNxcU53VGJjV1lOaUlGWHhiQlhPdGFEQ1NlbW40VFNCY2FURmRZVUJkaE5aZU9ZZUJuWmI1NjVpcFFYbjYwWDItenVidGIzM1czRzF1c3dObjhGcURMRElqUHRBQzducnlWWUlVU3VrZXVnZ1lVckhNQkF1R3dTcXNCc0dnTDdTZlJjNzRlTmctcWkxM3BOM2plRmZ1a0ExZjczaW5PcjlJR1dBU1RSU09fWnRVcG5DMkFqbU44R00tWGljdUZVZHVLbDNFYWVEdHB0QmZLY3U0VGQ5TjdqSDFQdUdnc1oyMV9WWHB3Vl9qUG1UTTFwWjVwX29wbFQ5VWIxUVdpLThXdmMteThadVJtamxrczRNZzVtX2gwcnVZQUkxU18zSTRjZjV6eFhWUDJoRTlfaWQtMFFRWjNtRXciLAoidXNlIjogInNpZyIKfQ=="
#        jwks-uri: http://localhost:8089/
        issuer: http://localhost

#        keycloak-jwks-uri: http://localhost:8090/realms/master/protocol/openid-connect/certs
#        issuer: http://localhost:8090/realms/master