kumuluzee:
  name: "grpc client test"
  server:
    http:
      port: 8082
  grpc:
    clients:
    - name: client1
      port: 8081
      address: localhost
      keepAlive: 1000
      keepAliveTimeout: 1000
#      certFile: ../certs/server.crt
#      keyFile: ../certs/server.key
#      trustFile: ../certs/rootCA.crt